title: Sounding the Castle
description: A digital inventory of manuscripts, chant fragments, instruments, piano rolls, and performances.

theme: just-the-docs

url: https://YOURUSERNAME.github.io

baseurl: "/sounding-the-castle"

color_scheme: light

search_enabled: true

nav_sort: case_insensitive

aux_links:
  GitHub Repository:
    - https://github.com/YOURUSERNAME/sounding-the-castle
